
# %%
import datetime
from pathlib import Path

from arguslib.instruments.direct_camera import DirectUndistortedCamera
from arguslib.radar.radar_overlay_interface import RadarOverlayInterface
from arguslib.instruments.video_interface import VideoInterface

# --- Configuration ---
campaign = "COBALT"
camstr = "3-7" # Or another DirectUndistortedCamera
output_dir = Path(__file__).parent / "output" / "radar_progression_videos"
output_dir.mkdir(exist_ok=True, parents=True)

# Video time parameters (same as before, adjust as needed)
video_start_dt = datetime.datetime(2025,5,11,11,57)
video_end_dt = datetime.datetime(2025, 5,11,12,3)
video_frame_step = datetime.timedelta(seconds=10)
video_fps = 2

# Radar and plot settings (customize these)
# These kwargs will be passed to VideoInterface.show(), which in turn
# passes them to RadarOverlayInterface.show().
video_and_overlay_show_kwargs = {
    # For DirectCamera (target_instrument of RadarOverlayInterface)
    "brightness_adjust": 1.0,

    # For RadarOverlayInterface annotations (controlled by its show method)
    "annotate_beams": True,
    "beam_type": "active", # Only show the active beam
    "kwargs_radar_beams": {"color": "magenta", "lw": 1.5}, # Label will be auto-generated by RadarOverlayInterface
    "annotate_scan_box": True, # Show the scan extent box
    "range_km_scan_box": 15.0, # Example: different range for scan box
    "kwargs_scan_box": {"color": "cyan", "linewidth": 0.7, "label": "15km Scan Box"},
}
# --- End Configuration ---

print(f"Initializing DirectUndistortedCamera '{camstr}' and RadarOverlayInterface...")
camera = DirectUndistortedCamera.from_config(campaign, camstr)
radar_overlay = RadarOverlayInterface.from_campaign(
    campaign, {"type": "DirectCamera", "camstr": camstr}
)  # Note: config for target instrument

# --- Prepare video interface ---
video_iface = VideoInterface(radar_overlay)
output_video_filename = output_dir / f"radar_progression_{campaign}_{camstr}_{video_start_dt.strftime('%Y%m%dT%H%M%S')}.mp4"
print(f"Attempting to generate video: {output_video_filename}")

# --- Generate video using VideoInterface.generate_video ---
video_iface.generate_video(
    output_path=str(output_video_filename),
    start_dt=video_start_dt,
    end_dt=video_end_dt,
    step_timedelta=video_frame_step,
    fps=video_fps,
    show_kwargs=video_and_overlay_show_kwargs, # These kwargs are passed to RadarOverlayInterface.show()
    time_overlay=True
)

print(f"Video generation complete. Saved to {output_video_filename}")
# %%
